/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adapters.shortest.paths.impl.jython_networkx;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
